### ISSUE TITLE
RC1 Plugin doesn't show up after installing

### ISSUE THREAD

**Issue by karnwatcharasupat** [OllisGit/OctoPrint-PrintJobHistory#1]
After installing via URL, the pop-up shows 'unknown' plugin and after a restart, there is no tab for the Job History plugin

**Comment by OllisGit** [comment]
Wow, rc1 is out for round about 2h and already tested!

The current sourcecode includes "death-code" which is referencing to the lib "opencv". I need to cleanup the code... take some hours.

Thx, for your feedback
Olli

**Comment by OllisGit** [comment]
fyi: takes more time to fix. I deleted rc1!

**Comment by OllisGit** [comment]
Hi @karnwatcharasupat ,

RC2 is out! 
Please test and give me a feedback.

Thx, in advance
Olli

**Comment by karnwatcharasupat** [comment]
Thanks a lot! We will test it out and update you :)

**Comment by karnwatcharasupat** [comment]
The RC2 now can be installed :)
