### ISSUE TITLE
Simplify 3d - Settings

### ISSUE THREAD

**Issue by gdcircuit** [OllisGit/OctoPrint-PrintJobHistory#100]
Please add support for capturing simplify 3D Slicer settings which follow a different format.

**Comment by gdcircuit** [comment]
Here is an example simplify 3d file.

**Comment by OllisGit** [comment]
Hi @gdcircuit,

issue-answering with attaching an file is not possible with GitHub, you need to use the Web-UI to upload attachments.
BR
Olli

**Comment by RobinAHoward** [comment]
Does this work?

[flowRateCalibrationCube_0.8mmWalls.txt](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/6327382/flowRateCalibrationCube_0.8mmWalls.txt)

**Comment by gdcircuit** [comment]
Sorry for the late response. The email got buried. Yes this looks great. When will it be in a release? I am looking to upgrade to a new release because my plugin hasn’t been working for over a month. I have seen others with a similar issue so I figured a new release would fix it.

**Comment by OllisGit** [comment]
Hi,

new version 1.3.0 is out and now the Simplify 3d - Settings could be parsed. The current solution is not the best, but should work (see #144)

Please test and give feedback.

Thx, in advance
Olli

**Comment by RobinAHoward** [comment]
Looking good.  Tried it on 4 prints and doing what it should.  THANK YOU!
