### ISSUE TITLE
Add Slicer Specifications

### ISSUE THREAD

**Issue by toedtling** [OllisGit/OctoPrint-PrintJobHistory#101]
Hi! [FEATURE REQUEST]
Could you please add an readout Slicer Specifications like Layer hight or speed in the Plugin

Thanks a lot

**Comment by OllisGit** [comment]
Hi @toedtling ,

I am not sure what you want. Layer information is read from DLP-Plugin
![image](https://user-images.githubusercontent.com/24205767/104496243-05e3a000-55d9-11eb-9d16-cfc4b3ed0a5d.png)

What other information is needed, please give an example or screenshot.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
No Feedback -> closed!
