### ISSUE TITLE
Enable execution of system commands at the end of the print

### ISSUE THREAD

**Issue by FixxCZ** [OllisGit/OctoPrint-PrintJobHistory#117]
This is a new feature request:
My printer has LED lights that are operated via system commands Svetlo Vypnout, Svetlo Zapnout
![image](https://user-images.githubusercontent.com/46757804/108384128-beb98200-720a-11eb-9bb5-41f8c7449519.png)
Printer is in a dark room and problem is that when it finish it takes a completely black picture of the dark room while it would be useful to switch on the lights and then take a shot of the print.
Light can be operated by the system commands, so if I could set up what command should be executed before the camera take a picture and ideally switch it off after, that would be great.
Thanks for your great work you did so far!

**Comment by OllisGit** [comment]
Hi @FixxCZ,
I understand the issue, but the purpose of this plugin is to capture print job data and not to execute some other actions.

You can take a look into the plugin-repository. I think here you will find the correct solution.
E.g. https://plugins.octoprint.org/plugins/gcodesystemcommands/

Hope that helps!
