### ISSUE TITLE
Reload past prints from PrintJobHistory and Print

### ISSUE THREAD

**Issue by BraveSolo** [OllisGit/OctoPrint-PrintJobHistory#124]
It would be very convenient for me to review the prints in the Print Job History, and then load and reprint them directly from the Print History.  I have a print farm and it would be faster to review the past prints and print them from the PrintJobHistory.

**Comment by OllisGit** [comment]
fyi: Feature is already planed (long-term), see https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1#card-45793778
I closed this issue to cleanup the "bug-tracking", but the feature is still planed (if not, it will be moved to column done in future).
