### ISSUE TITLE
Pb to install plugin

### ISSUE THREAD

**Issue by jmlg10** [OllisGit/OctoPrint-PrintJobHistory#126]
Hello,

I'm trying to install your plugin on my windows corporate computer, but I guess that some security policies apply and I can't.

To install octoprint I have had to use "--trusted-host files.pythonhosted.org etc.." option and it worked.
But I can't find a way to use this option for installing your plug-in...

Any Hints?
![Capture_issue_plug-in](https://user-images.githubusercontent.com/33903686/113401144-38649400-93a3-11eb-8dbe-829de75faed3.PNG)

Many thanks

**Comment by OllisGit** [comment]
Hi @jmlg10,
I don't have a direct solution about the SSL-issue, but you can install the plugin "by hand"

- download the plugin via your browser into your filesystem: https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/latest/download/master.zip
- go into the settings and open the plugin manager menu, click on "Get more" and select the zip file from your filesystem.

Hope that helps. 
Olli
