### ISSUE TITLE
Feature request: export print history

### ISSUE THREAD

**Issue by jmlg10** [OllisGit/OctoPrint-PrintJobHistory#127]
Hi,

I'm trying to install PrintJobHstory as said in another "#issue"

I hope I shall find a way to make it running, but meanwhile I have one question.
It looks like it is possible to connect to the server and ask for exporting the file in CSV format.
But this is interactively.
I was wondering if there is any possibility to export it to a server location (or via eamil ) automatically after each print or each end of day?
Let me know.

Many Thanks

Jean-Michel

**Comment by OllisGit** [comment]
Hi @jmlg10,
currently this feature is not "directly" planed!

The main purpose of the plugin is to grab the job data and store it to a sql-database. Storing the data to an other target (like cloud-storage, Google-Sheets, etc.)  is out of scope, BUT...

...one option I was thinking about is, to fire an event with all job informations to the Octoprint-Eventbus. 
With this feature it should be very easy to write your own plugin to push the job-data where ever you like.
Tracked in https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1#card-32836851

**Comment by jmlg10** [comment]
Hi,

On the other hand, I want to generate a dashboard using the datas of the print history in PowerBI.
This software is able to analyze SQL databases, could it be possible to connect to your SQL server?

Let me know.

Cordialement / Best Regards

Jean-Michel LE GOFF | Responsable Recherches Numériques | Louis Vuitton Malletier | 2, Rue du Pont-Neuf, 75001 Paris, France | Phone: +33 155803048 | Mobile : +33 664405492 | Email address:  ***@***.***

De : OllisGit ***@***.***>
Envoyé : dimanche 11 avril 2021 22:24
À : OllisGit/OctoPrint-PrintJobHistory ***@***.***>
Cc : Jean-Michel LE GOFF ***@***.***>; Mention ***@***.***>
Objet : Re: [OllisGit/OctoPrint-PrintJobHistory] Feature request: export print history (#127)

________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Hi @jmlg10<https://urldefense.com/v3/__https:/github.com/jmlg10__;!!Lt0KOR8!B9THSU5K2uGuCIRviRoJbtv0IRldDro28NMrUvzT4hVohqbehUu0q7XySnEDJ_UClnUmruiMsP2GBA$>,
currently this feature is not "directly" planed!

The main purpose of the plugin is to grab the job data and store it to a sql-database. Storing the data to an other target (like cloud-storage, Google-Sheets, etc.) is out of scope, BUT...

...one option I was thinking about is, to fire an event with all job informations to the Octoprint-Eventbus.
With this feature it should be very easy to write your own plugin to push the job-data where ever you like.
Tracked in https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1#card-32836851<https://urldefense.com/v3/__https:/github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1*card-32836851__;Iw!!Lt0KOR8!B9THSU5K2uGuCIRviRoJbtv0IRldDro28NMrUvzT4hVohqbehUu0q7XySnEDJ_UClnUmrug14TbSMQ$>

**Comment by OllisGit** [comment]
Hi @jmlg10,
currently it is not possible, because I am using a local filebased database.
It is planed to use a sql-server (e.g. postgres), but this is still in development.

**Comment by jmlg10** [comment]
Ok,
I shall wait.
Let me know when it will be possible to try something.
Thanks
