### ISSUE TITLE
LOW: Update readme screenshots

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-PrintJobHistory#128]

**Comment by SM-26** [comment]
I'd be more than happy to help with this one.
just to take one care out of your head.

I'm guessing you are refereeing to 1.4.0?

**Comment by OllisGit** [comment]
Hi @SM-26,
thanks for the offer. 

If you think there is any kind of documentation missing (readme or wiki) feel free to raise a pull request or just add the missing information in this ticket.

For V1.13.0 I only updated one screenshot.

**Comment by SM-26** [comment]
I've made a commit with some new pictures.
https://github.com/SM-26/OctoPrint-PrintJobHistory/commit/5255800c8c9bd134ce855e83f2a46d05a4a96e1e

Made a new Wiki page
https://github.com/SM-26/OctoPrint-PrintJobHistory/wiki/Plugin-Setting-and-Setup/5b262b82c4b8243ca7c7e1056e496c98fe5bd000

Can I also ask you to make to wiki editable by anyone?
https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis
