### ISSUE TITLE
Prints Requiring Multiple Rolls of Filament Show Used Filament Incorrectly 

### ISSUE THREAD

**Issue by Quintin9801** [OllisGit/OctoPrint-PrintJobHistory#13]
When printing large objects that require multiple rolls of filament, The filament sensor on the machine is triggered and sends an M600 command to the printer and Octoprint to change filament, as well as a pause command for Octoprint.

Currently, the amount of filament on for multiple roll prints only counts the amount used until the filament is changed after the filament change the amount is not recorded in the history. The screenshot of Simplify3D's estimate is not as accurate as you would hope but there is a comparison of the projected amount of filament and the amount tracked by PrintJobHistory. 

In PrintJobHistorythe amount recorded is from what was left of a partial roll and it did count that roll correctly, But when I swapped out for a new roll, The count did not start again.

Currently, I do not have any GCODE scripts that execute before or after the print is paused because it is all handled by the printer's firmware.

![Print Job History Error](https://user-images.githubusercontent.com/35208750/71365584-1146d200-2565-11ea-81ea-3ab21685b875.PNG)
![Print Job History Error2](https://user-images.githubusercontent.com/35208750/71365585-1146d200-2565-11ea-8087-101213270f8c.PNG)

Additional Info:
Octoprint Version: 1.3.12 
PrintJobHistory Version: RC5
Printer: Modix Big 60 w/MKS Gen 1.4
Firmware: Marlin 1.1.9
Octoprint Server OS; Windows 10

**Comment by OllisGit** [comment]
Hi @Quintin9801 ,
first: Wow!!! 3 days and 10 our print, respect! What a cool big printer ;-)

After the print I am reading the values from the "FilamentManager-Plugin" and I think this plugin doesn't support filament change, see Isssue: https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/76

But my assumption is, after the change the used weight should continue increasing and not stopping....or do you use more then one extruder? Because currently I only support one extruder.

I will take a look after x-mas.
Olli

**Comment by Quintin9801** [comment]
@OllisGit 
Thanks for such a fast reply! To answer your question about the number of extruders, there is only one.

Have a merry x-mas sir,

Quintin

**Comment by OllisGit** [comment]
Hi @Quintin9801!

fyi:
Well, it took a while.....but currently I am continuing developing my spool-manager-plugin  and as a reference I use the FilamentManager plugin. 

There is an issue after the printer paused, everything is reseted and I don't know why he implement this "feature".
The evaluated extrusion length should only be reset, if you change the spool and the current length value should assign to the last spool.

**Comment by OllisGit** [comment]
Try to use the lastest PJH-Plugin V1.14.0 and SpoolManger V1.4.0, that should work!

Please test and give feedback!
Olli

**Comment by OllisGit** [comment]
No feedback. If needed raise a new ticket.
