### ISSUE TITLE
missing layer count

### ISSUE THREAD

**Issue by jmlg10** [OllisGit/OctoPrint-PrintJobHistory#132]
Hi,

I'm printing to octoprint from Fusion360

I'm wondering how did you count layers in a print job.
the Print history is showing no layers... but there are.
I've seen while processing a file from Simplify 3D that in this gcode you can eidentify Layers
is it via the M117 code? and the line "M117 INDICATOR-Layer2" ?

Or is there another way to tell PrintJobHistory to count layers?

Many thanks

**Comment by OllisGit** [comment]
Hi @jmlg10,

the layer-informations is provided by the "DisplayLayerProgress-Plugin". So, this needs to be installed!
