### ISSUE TITLE
1.11.1-dev conflicts with UI Customizer

### ISSUE THREAD

**Issue by NguyenTanBao** [OllisGit/OctoPrint-PrintJobHistory#134]
I'm not sure which plugins are the root case but since I haven't changed UI Customizer, only change PrintJobHistory so I posted here.

1.10.0 version works fine with UI Customizer

1.11.1-dev  version causes any artifacts on the screen and complete breaks the layout that UI Customizer does.
![image](https://user-images.githubusercontent.com/29285869/114479067-89029b00-9bb4-11eb-90b9-930f424314cb.png)

Few other observations:
* It actually also causes some weird behavior when interacting with SpoolManager selection on the sidebar. 
* Clicking on a print, can't load data when UI Customizer is enabled.

**Comment by jangrewe** [comment]
@OllisGit: can confirm.

**Comment by codingcatgirl** [comment]
Same here.

**Comment by OllisGit** [comment]
duplicated, see #137
