### ISSUE TITLE
Print History not visible after manual add of print

### ISSUE THREAD

**Issue by taker218** [OllisGit/OctoPrint-PrintJobHistory#140]
So I just added a print via the "Add printjob" and now all the prints are invisible.
But when I go to statistics, I get all the statistics shown, including the new one I added (had 609 prints before, now it's 610).

![2021-04-19 12_58_24-Window](https://user-images.githubusercontent.com/15029277/115225957-f5c6e980-a10e-11eb-86fd-00a8bb74ba41.png)
![2021-04-19 12_58_17-Window](https://user-images.githubusercontent.com/15029277/115225959-f65f8000-a10e-11eb-8cd8-4920c78e9742.png)

Version is the latest 1.12.dev1.

Any idea why this is happening? Or is there any logging I can activate to see what's going on?

**Comment by taker218** [comment]
Okay, I just clicked on one of the sortings and now the prints are there again, but it seems like I can't show the page with the manually added print.
All other pages show just fine, only the one with the new print doesn't show up.

**Comment by taker218** [comment]
I attached my database, with just the last "normal" print and the one I added through the plugin. As well as the octoprint.log from the last startup.

the screenshot shows which information I provided.
<img width="739" alt="issue140_printjobhistory" src="https://user-images.githubusercontent.com/15029277/115235932-08dfb680-a11b-11eb-9067-400dab1c06c2.png">
[issue140_printjobhistory.zip](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/6336028/issue140_printjobhistory.zip)

**Comment by OllisGit** [comment]
Hi,

new version 1.3.0 is out and should fix the issue.

Please test and give feedback.

Thx, in advance
Olli

**Comment by taker218** [comment]
Just installed the new version and now I can add a new print and it shows up in the gui.
