### ISSUE TITLE
Print Job Dialog does not appear after successfull print

### ISSUE THREAD

**Issue by realbadfox** [OllisGit/OctoPrint-PrintJobHistory#141]
Since last update, the Dialog after a successfull print does not appear, and was not saved.

**Comment by realbadfox** [comment]
[octoprint.log](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/6342221/octoprint.log)

**Comment by zhechenzhu** [comment]
save error message here. 'SpoolmanagerPlugin' object has no attribute 'myFilamentOdometer'

**Comment by adam5zki** [comment]
I have the same issue. same error in the octoprint.log.

**Comment by EvilBlood** [comment]
Same over here

**Comment by chimcen** [comment]
Here the same - the fix from older version doesn't work anymore...

**Comment by realbadfox** [comment]
installed last working Release V1.10.0, with that it is working

**Comment by speedysk1** [comment]
Add me to the list of the plugin no longer working.  :(

**Comment by melvinmicallef** [comment]
not working.. i dont see it worth it to switch to filament manager from spool manager just cause of this bug..so sadly i will have to uninstall this plugin

**Comment by Filmman586** [comment]
I'm having the same issue. It use to work great but now it doesn't. After a successful print, nothing happens. I used to get the edit dialogue window, now nothing, and now I have to refresh my window for the print to show up.

**Comment by mediamanrit** [comment]
I'll add a me-too here.  No tracebacks in the octoprint log file though.  Still investigating.  It's not due to SpoolManager or FilamentManager conflicts in my case as I had neither installed when this started happening.

**Comment by OllisGit** [comment]
Hi,

new version 1.3.0 is out and should fix the issue.

Please test and give feedback.

Thx, in advance
Olli

**Comment by mediamanrit** [comment]
> Hi,
> 
> new version 1.3.0 is out and should fix the issue.
> 
> Please test and give feedback.
> 
> Thx, in advance
> Olli

Seems to be working now consistently.  Thanks!

**Comment by chimcen** [comment]
This was working since 1.13.2 in combination with Filament Manager again…
