### ISSUE TITLE
CSV import/reimport on v1.13.2

### ISSUE THREAD

**Issue by chimcen** [OllisGit/OctoPrint-PrintJobHistory#146]
Hi,

after actualizing to latest PJHv1.13.2 i've tryed to reimport my old csv export and get only some errors.

I thought, there could be some changes within the csv layout, so i've deleted the database and added a sample print within PJH manually.
After then i've exported this to csv, deleted the database again and tried to reimport the prev. export - ending also in error messages:

![image](https://user-images.githubusercontent.com/22658487/118943386-da404000-b953-11eb-8c7c-b149c305acd1.png)

Can you help?

**Comment by chimcen** [comment]
Replacing the not parsable values (except used weight), the import is possible:
![image](https://user-images.githubusercontent.com/22658487/118977117-1ab0b580-b976-11eb-996d-f5e7a1f21fc1.png)

**Comment by OllisGit** [comment]
Hi,
in the latest release V1.14.0 the issue should be fixed.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by chimcen** [comment]
Hi Olli,

CSV Import works now.
But there is a problem with Spool Manager and PHJ togehter - i'll post this in Spool Manager git...
