### ISSUE TITLE
Small "funny" typo ;-)

### ISSUE THREAD

**Issue by BerndJM** [OllisGit/OctoPrint-PrintJobHistory#15]
Correct List view:
![Auswahl_051](https://user-images.githubusercontent.com/1837889/72858720-04331500-3cc2-11ea-8a24-a1eb4a2396a9.png)

And than ... the edit view:
![Auswahl_052](https://user-images.githubusercontent.com/1837889/72858731-11e89a80-3cc2-11ea-96dc-d16f2e86f658.png)

Btw. it would be nice to see also the used weight in the list view, because this is IMHO the more common measurement and fits better to the information from the filament manager plugin.
Just my 2¢ ;-)

**Comment by OllisGit** [comment]
Hi @BerndJM ,
thanks a lot for your 2¢ !!

Will be fixed in the next release.

Please be patient.
Olli

**Comment by OllisGit** [comment]
In the next release the ui-output will be "m" and in the csv-output/input will be "mm".

**Comment by OllisGit** [comment]
Hi,
it's fixed in the new release candidate, see release description: https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.0.0rc6
