### ISSUE TITLE
Enhancement: Custom data fields

### ISSUE THREAD

**Issue by Pun-e** [OllisGit/OctoPrint-PrintJobHistory#157]
Octoprint is gradually penetrating education and professional printing labs where the ability to add custom fields would be of great use. For example a "Project" field, so users can easily group, track, and eventually bill print jobs with great accuracy and accountability. Or simply to track other changes the user might make such as nozzle width, or chamber temperature.

The current notes section *could* be of use, but they're not searchable within the plugin so are at best a workaround.

Either way, I'm a very happy user and am successfully using your plugin on my home and work printers to great effect!

**Comment by OllisGit** [comment]
Hi @Pun-e,

it is a good idea, maybe you have also a suggestion how the user should manage such fields.

I mean:
- What kind of fields should be supported (text, number, selection-list, date, time, ...)?
- How to layout such fields?
- Each field should be searchable (of course)

I am not a UI professional, so adding a fully customizable drag&drop authoring tool is an absolut no go for me.
So maybe you have easy solution and give me a screenshot how it could looks like.

Searchable Note-Filed is on my list.
