### ISSUE TITLE
Filament tracking resets after restart of octopi

### ISSUE THREAD

**Issue by LASaether** [OllisGit/OctoPrint-PrintJobHistory#158]
After selecting tool for Filament tracking and saving settings, the plugin works as intended. But after restarting the raspberry pi 3B+ running OctoPrint 1.6.1, the settings are switched back to "none" and I get a pop up notification that filament tracking is now possible.

**Comment by donlook** [comment]
@LASaether -- See issue #149

**Comment by OllisGit** [comment]
Hi,
new release [1.15.0](https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.15.0) is available and fix this issue.

Please test and give me a feedback. 
Thx, in advance!
Olli
