### ISSUE TITLE
Filament Usage In Statistics Popup Is Incorrect

### ISSUE THREAD

**Issue by donlook** [OllisGit/OctoPrint-PrintJobHistory#161]
When you click on the "Statistic" link in the Print Job History tab, the filament usage statistics are overstated. I selected a date range that included only one job for this example.

![Job](https://user-images.githubusercontent.com/17184497/125137663-c18e1400-e0d2-11eb-83b1-491a44dff0a9.png)

![JobForm](https://user-images.githubusercontent.com/17184497/125137060-8b03c980-e0d1-11eb-9f0e-dbcf44b0fab2.png)

When you click on the statistic report link, the filament usage numbers in this case are double what is shown in the job tab. The job tab reports the usage as 4.29 m and the statistic tab reports 8.58 m. The used weight is also doubled. 

![Statistics](https://user-images.githubusercontent.com/17184497/125136669-e5505a80-e0d0-11eb-98fe-9e6a3a1270ad.png)

I believe that this is due to the rows in the pjh_filamentmodel table for this job, in my case there are two, one for toolId "tool0" and one for toolID "total". Should the statistics report look only at the "total" tool ID row?

**pjh_printjobmodel table**
![JobSQL](https://user-images.githubusercontent.com/17184497/125137536-8390f000-e0d2-11eb-8f0e-519d6225cb7c.png)

**pjh_filamentmodel table**
![filamentSQL](https://user-images.githubusercontent.com/17184497/125137546-8986d100-e0d2-11eb-9440-ed8dafd8aedd.png)

**Comment by OllisGit** [comment]
Hi @donlook, 
new release [1.15.0](https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.15.0) is available and implement  the patch from @hvraven (Thx, again)

Please test and give me a feedback.

BR
Olli

**Comment by donlook** [comment]
Hello @OllisGit,
When I install this update, all my job history does not show. It looks like the database structure update is not completing successfully? Someone else posted an issue #174  with at trace that the pjh_costmodel table is missing.
I have been able to reinstall 1.14.0 and the history is visible again.
Don

**Comment by donlook** [comment]
Hello @OllisGit,
The statistics are correct now.
