### ISSUE TITLE
Issue: Cyclic deselecting "filament tracker" setting

### ISSUE THREAD

**Issue by SatarisGIT** [OllisGit/OctoPrint-PrintJobHistory#165]
Hello!

I have problem with save settings for Print job history plugin. If I select "preferred filament tracker" as SpoolManager-Plugin, my setting constantly after some time will become deselected. After 3-4 prints or restart system, if I go to settings I can see thats selected preferred filament tracker is "None". When option is set as none, plugin totally not working correctly, not counting any weights or filament usages, so it is for me unusable. Is there any method for setting this ,,SpoolManager plugin" option permanently?

![image](https://user-images.githubusercontent.com/28608081/127912099-af5d74ee-eb27-40f9-86dd-b5aea1603cb1.png)

**Comment by ivgh1992** [comment]
First of all, thank you @OllisGit for your great job. Sadly I`ve been having the same problem. Every time I shutdown or restart octoprint the selections jumps back to "None". Hope you can fix this. Thank you @OllisGit

**Comment by eacxx** [comment]
Hi guys!
I'm in the same boat.
For me it's not after every restart or shutdown, but after 3 or 4 is happening for sure.
If somebody has a hint for those of us being less lucky then the rest, it would be more than welcome.

Thanks in advance.

**Comment by donlook** [comment]
Look at issue #149

**Comment by eacxx** [comment]
Thank you so much man!
And thanks to @ManuelMcLure especially.
I didn't tried yet, because I have a print rolling right now and I guess I can't restart Octoprint during it. I'm too new in this business so I don't know. I prefer to wait for the printer to finish.
But it looks to me that you really figured out the issue.
I'll come back with the feedback after I'll test.

**Comment by OllisGit** [comment]
Duplicated with #149

**Comment by OllisGit** [comment]
Hi,
new release [1.15.0](https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.15.0) is available and fix this issue.

BR
Olli
