### ISSUE TITLE
Date Formatting Option

### ISSUE THREAD

**Issue by blooest** [OllisGit/OctoPrint-PrintJobHistory#167]
Being an American who uses [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601#Dates) religiously, particularly given _OctoPrint already shows dates in that format_, seeing DD.MM.YYYY for the date formatting is irrationally bothersome. This extends to all of your plugins, but this is the one where it sticks out the most.
I'd like to see the option to customize the formatting to our liking, or at least to standardize to YYYY-MM-DD. Thanks!

**Comment by OllisGit** [comment]
I have no idea why the issue has a thumbs-down....this is on my list like the unit-formatting from mm to m or g to kg.
