### ISSUE TITLE
spelling - it is nozzle not nozzel 

### ISSUE THREAD

**Issue by mark-hahn** [OllisGit/OctoPrint-PrintJobHistory#17]
A minor ui typo:  It is nozzle not nozzel.

**Comment by OllisGit** [comment]
Hi @mark-hahn ,
thanks a lot for pointing me out!
Will be fixed in next version.

**Comment by OllisGit** [comment]
Hi,
it's fixed in the new release candidate, see release description: https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.0.0rc6
