### ISSUE TITLE
Feature request : Auto-add to ics file after print

### ISSUE THREAD

**Issue by pracovnik** [OllisGit/OctoPrint-PrintJobHistory#170]
I would like to ask, if there could be an auto-export-append into ics file after print.

Backstory:
I have in octoprint end gcode a (plugin: action commands) python script, that check logs and with data gathered, it export it into a icalendar file (ics) one entry is append.  I have shown it to few people on FB and they told me that they want it too. As I think, this is the most near plugin that has all the information, I wanted to ask it as a feature request.

Via badly configured haproxy, I have the ics file exposed to local network. And with ical client, on PC MS Outlook, on Android ics sync, shown as calendar.

![2021-09-13 18_47_42-Printer - Internet Calendars - Outlook](https://user-images.githubusercontent.com/40662523/134349785-0c83554f-61e1-4ed2-a564-cc98538cca32.jpg)

[log_to_ical.py.txt](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/7210935/log_to_ical.py.txt)

**Comment by OllisGit** [comment]
Hi @pracovnik,

if I understand you correct you want an other export functionality. Beside the CSV-Export, there should be ics-File export.
The export file include all selected printjobs as an event entry, right?
![image](https://user-images.githubusercontent.com/24205767/141633353-19ee961f-cd01-45aa-82bf-82047028412f.png)
 
In the next version there will be a print-job-template where the user can design a printing-layout in a jinja2 file and upload it to OP.
I think it will be easy to implement the same feature for the ics-feature.
The ics-template could look like this (pseudo-code):
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ical.marudot.com//iCal Event Maker
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
....
foreach(job in allPrintJobs
  BEGIN:VEVENT
  DTSTAMP:20211113T110702Z
  UID:1636801614876-36929@ical.marudot.com
  DTSTART;TZID=Europe/Berlin:20211122T120000
  DTEND;TZID=Europe/Berlin:20211122T120000
  SUMMARY:Print of {{job.printJobName}}
  DESCRIPTION:Print used: ....
  END:VEVENT

...
END:VCALENDAR
```

**Comment by pracovnik** [comment]
@OllisGit 
yes, exactly. 

Will it also have something like automatic export based on template/ics after each print ?
