### ISSUE TITLE
[Bug] Used length and weight significantly lower than it should be

### ISSUE THREAD

**Issue by lightmaster** [OllisGit/OctoPrint-PrintJobHistory#171]
I noticed that ever since May 16, 2021, there has be a fairly large discrepancy between the estimated lengths and weights of filament needed for prints (sliced using PrusaSlicer) and what PrintJobHistory reports as the actual amounts used. As far as I'm aware, nothing was really changed in slicer settings or with my printer (besides typical software update checks) around the time when I had the first reported discrepancy. And the differences aren't insignificant. For instance, a print a did yesterday, the Estimated Filament length was 25.50m and 76.07g, and the reported actual used was 6.97m and 20.79g. Not sure how this plugin gets the actual filament used (whether it records it as it prints or if something else records it while printing and this plugin just taps into that), so I'm not sure if its an issue with this plugin or some other plugin. I do know that SpoolManager decreased in weight from 143g to 122.2g, which matches with the "actual" amount used.

I watched as a print was going on yesterday, and the reported distance on the Octoprint dashboard did show very close to the estimated amount right before the print finished, but as soon as the PrintJobHistory window popped up, the "used length" showed 4-5x lower than it should have.

**Comment by OllisGit** [comment]
Hi @lightmaster,

to analyse the issue I need more informations:

- printed gcode
- octoprint.log of that print
- expected values (e.g. screenshot from slicer, dashboard, ...)
- measured value from PJH 
- what plugins/versions do you use
