### ISSUE TITLE
filament tracking not possible popup

### ISSUE THREAD

**Issue by madnlooney** [OllisGit/OctoPrint-PrintJobHistory#177]
Seem to be getting this pop up everytime I start octoprint UI. ive got settings to not ask about spool managers
![error](https://user-images.githubusercontent.com/29359054/141866378-94c85ddf-941e-40a0-b433-211ab903129a.PNG)

**Comment by OllisGit** [comment]
Hi @madnlooney,

in the latest release 1.15.2 there is a checkbox you need to activate to not see the reminder box again.

Please test and give feedback.

Thx,
Olli

**Comment by madnlooney** [comment]
yes new check box has stopped the popup
