### ISSUE TITLE
[Enhancement] Include Weight from FilaWeigher

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-PrintJobHistory#18]
Instead of calculated used weight use the real measured value.
http://automatedhome.party/2019/12/14/the-filaweigher-a-standalone-wifi-web-based-weight-sensor-for-3d-printer-filament-for-less-than-7/

**Comment by Wob76** [comment]
+1 for this feature, I just received my load cell to build my own Filaweigher so would love to see this feature.

**Comment by Wob76** [comment]
I have my unit built, just need to mount it to my enclosure. I have it working with his basic Octoprint plugin, if you need any testers to progress integration please let me know.
