### ISSUE TITLE
Can't turn on Filament tracker

### ISSUE THREAD

**Issue by Mathew-D** [OllisGit/OctoPrint-PrintJobHistory#182]
The cost will not auto add to the history anymore.  When I try and turn on the tracking I get a mouse curror with an X. I have both Filament tracking ad's installed and the cost shows up on other sections of Octoprint.   Any idea why it will not allow my to turn on either plugin for history?

I am running the newest version on the addons.

![image](https://user-images.githubusercontent.com/44036272/143665911-457851a1-b413-4cb9-8e6f-410c629cd28c.png)

![image](https://user-images.githubusercontent.com/44036272/143665977-6f3db1fb-6f6e-4617-9eb8-c52a762689b0.png)

![image](https://user-images.githubusercontent.com/44036272/143665982-aabfbd4c-cd08-4b5c-b044-68a78fcf9f33.png)
![image](https://user-images.githubusercontent.com/44036272/143665985-cf519214-da04-481e-9ecf-fa6ca3abe3b6.png)
![image](https://user-images.githubusercontent.com/44036272/143665998-9412039d-19d3-417c-9034-516fd5ebd330.png)

**Comment by OllisGit** [comment]
Hi @Mathew-D,
please update to SpoolManager 1.6.0 and try again.

Maybe there is a JavaScript-Bug. Please open the Browser-Dev Tools Console (press F12) there should be no red messages.

**Comment by lightmaster** [comment]
I'm seeing this issue with PrintJobHistory v1.16.0 and SpoolManager v1.6.1. Spool Manager is greyed out. The button had already been selected in a previous version, so it's still selected and shows the filament data in Print Job History. Will check after this print to make sure that Spool Manager is adjusting remaining filament correctly.
