### ISSUE TITLE
No Print Job History since tHE 26th ("bad transparency mask")

### ISSUE THREAD

**Issue by Filmman586** [OllisGit/OctoPrint-PrintJobHistory#184]
All of a sudden I lost my print job history. I deleted the database and recreated, still have nothing. Attached my log File. Anything else you need?
[octoprint.log](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/7614179/octoprint.log)

**Comment by Filmman586** [comment]
I still can't get a history, I even reinstalled everything. Please help...

What do you need from me

**Comment by Filmman586** [comment]
I think there is an issue with Pruser Slicer Thumbnails and Print Job History. I have both Cura Thumbnails and Prusa Slicer Thumbnails installed. I recently installed Prusa Slicer to try it out and thats when the problem started. I installed Prusa Slicer Thumbnails and I had no reports being generating, I disabled Prusa Slicer Thumbnails and my reports are back. Could there be a conflict with the 2?

**Comment by OllisGit** [comment]
Hi @Filmman586,

please attach a prusa sliced gcode with the included thumbnail-image. It looks lie that the prusa-slicer changed the format and what version of prusasclicer do you use?

I tested with old prusa-gcode file and it works.

**Comment by OllisGit** [comment]
With the following description and CURA I was able to reproduce the issue. Thx, @net147 for providing the link.
https://github.com/mriscoc/Marlin_Ender3v2/wiki/How-to-generate-a-gcode-preview

I will work on a solution...

**Comment by OllisGit** [comment]
Hi @Filmman586,

new release is out and fixed the issue.

Please test and give feedback.

Thx, in advance
Olli

**Comment by net147** [comment]
Works for me

**Comment by Filmman586** [comment]
Olli,

Tested it. I've attached a screen shot. Both settings in Cura Thumbnails and Slicer Thumbnails are the same. And the background is black, and scaling is off. Take a look...


________________________________

**Comment by OllisGit** [comment]
@net147 sending emails with attachments to GitHub-Issues is not working. You need to attach the images directly in the GitHub-UI.

**Comment by Filmman586** [comment]
Olli,

Tested it. I've attached a screen shot. Both settings in Cura Thumbnails and Slicer Thumbnails are the same. And the background is black, and scaling is off. Take a look...

![Screenshot 2022-01-23 051649](https://user-images.githubusercontent.com/83276762/150848836-d96a417f-9cbe-4647-88ed-c8bc2b090a9f.png)
