### ISSUE TITLE
Filament tracking not working

### ISSUE THREAD

**Issue by bambuleee** [OllisGit/OctoPrint-PrintJobHistory#187]
Spool is selected for printing.
![image](https://user-images.githubusercontent.com/10706472/144146278-a52d94ba-2735-41f7-911c-a387d0999200.png)

But in the finished print dialog it's not recognized. Stop working from one day to another.
Reinstalled PrintJobHistory plugin and Sppol Manager.

![image](https://user-images.githubusercontent.com/10706472/144146372-1906c70e-5a66-4cbd-bc69-5936269e3e35.png)

Tried with different spools.

**Comment by OllisGit** [comment]
Hi,
I found in the logs that the needed filament was not provided by octoprint. That is the reason why the spool information is not tracked.
```
INFO - There is no calculated filament data in meta-file
```
The calculation is done during an "analyse-phase". The result is stored in the upload folder like this:
```
<OP>/uploads/metadata.json
  "3DBenchy.gcode": {
    "DisplayLayerProgress": {
      "totalLayerCountWithoutOffset": "159"
    },
    "analysis": {
      "estimatedPrintTime": 3529.315478428196,
      "printingArea": {
        "maxZ": 48.05,
        "maxX": 119.791,
        "maxY": 122.755,
        "minX": 20.0,
        "minY": 50.0,
        "minZ": 0.3
      },
      "dimensions": {
        "width": 99.791,
        "depth": 72.755,
        "height": 47.75
      },
      "filament": {
        "tool0": {
          "volume": 10.928834037976793,
          "length": 4543.68119999991
        }
      }
    },
```
Please check if the "analyse-feature" is activated like this:
![image](https://user-images.githubusercontent.com/24205767/149666444-adf28ed4-35d6-41a8-8b3a-9160f9199180.png)

**Comment by bambuleee** [comment]
Hi,
the setting was not checked on always, but this with "always, it is not working
[octoprint.log](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/7881441/octoprint.log)
.

**Comment by bambuleee** [comment]
I did a new installation (switch from octopi to octoprint-docker) with new settings, only backup from spool manager.
It is working now.
