### ISSUE TITLE
Fails to capture print job due to "bad transparency mask" while capturing thumbnail

### ISSUE THREAD

**Issue by net147** [OllisGit/OctoPrint-PrintJobHistory#190]
I tried doing a some test prints and it failed to capture the print job.
I am using Cura 4.13.0 with GCode Preview script from https://github.com/mriscoc/Marlin_Ender3v2/wiki/How-to-generate-a-gcode-preview and PrintJobHistory 1.15.2.

Here is the octoprint.log file:
[octoprint.log](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/7876532/octoprint.log)

**Comment by OllisGit** [comment]
Thank for reporting! The issue is duplicated and will be tracked here #184. 
Also please attach your ```EN2_Elephant_-_Voronoi2.gcode``` to that ticket.

Thx, in advance
