### ISSUE TITLE
Not an issue, just a suggestion

### ISSUE THREAD

**Issue by SaddamoDeBeers** [OllisGit/OctoPrint-PrintJobHistory#192]
First of all, I do absolutely like your plugins!

What if:

You could add settings for dedicated mysql server database located somewhere else than on your raspberry.
What if you are running more than 1 printer, maybe these printers could upload database somewhere else and share it between.
I am writing this, if you do use spool manager plugin and you are switching one spool between few printers, maybe that data from spools could be shared between printers too, if they run octoprint ofc.

This could be just optional feature. I have no idea how hard it could be to do it, but maybe somebody has extra raspberry pi running mysql at home or somewhere else mysql running machine.

Thank you very much for all plugins!

**Comment by OllisGit** [comment]
Hi @SaddamoDeBeers, 
the external database feature is already on my list. I am currently preparing a dev release of SpoolManager with the external database feature. After this is out, PJH will also become this feature. 

Closed, duplicated #45
