### ISSUE TITLE
BUG: Duplicate webcam id (webcam_rotator) problem

### ISSUE THREAD

**Issue by LazeMSS** [OllisGit/OctoPrint-PrintJobHistory#194]
https://github.com/OllisGit/OctoPrint-PrintJobHistory/blob/433a1c9da14048ebb6af6b132c8a8226b3e873a2/octoprint_PrintJobHistory/templates/PrintJobHistory_tab_dialogs.jinja2#L453

Same problem as:
https://github.com/mikedmor/OctoPrint_MultiCam/issues/47

**Comment by OllisGit** [comment]
Hi @LazeMSS,
fixed in latest release V1.17.0
