### ISSUE TITLE
Information page not showing properly

### ISSUE THREAD

**Issue by abecaw** [OllisGit/OctoPrint-PrintJobHistory#196]
when print is finished a popup is displayed.  The popup looks like it is left justified..  Also when i pull up a previous print job history file it is the same left justified.  All i get is one page see attachment  
![Screenshot 2022-04-02 20 09 06 (1)](https://user-images.githubusercontent.com/58127207/163625103-8a424127-8af5-488f-8c11-6c02cef27904.png)

**Comment by norbou2** [comment]
Hi, I have a similar problem, I installed PrintJobHistory and SpoolManager. I can see the length and weight data correctly, but the price is not calculated according to the data entered in SpoolManager. So in the job listing I can see the lengths and weights, but the price is listed as zero.
