### ISSUE TITLE
Plugin manager states update is available but it will not install

### ISSUE THREAD

**Issue by joeySeal** [OllisGit/OctoPrint-PrintJobHistory#2]
Octprint update manager will not update to rc2

`2019-11-03 19:33:02,261 - octoprint.plugins.softwareupdate - INFO - Starting update of PrintJobHistory to 1.0.0-rc2...
2019-11-03 19:33:39,160 - octoprint.plugins.softwareupdate - INFO - Update of PrintJobHistory to 1.0.0-rc2 successful!
2019-11-03 19:33:39,345 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2019-11-03 19:33:39,348 - octoprint.plugins.softwareupdate - INFO - Restarting...
2019-11-03 19:33:39,538 - octoprint.server - INFO - Shutting down...
2019-11-03 19:33:39,682 - octoprint.events - INFO - Processing shutdown event, this will be our`
![print_history](https://user-images.githubusercontent.com/2881557/68094717-41c99400-fe71-11e9-8e7c-8dd0a961765e.png)

**Comment by OllisGit** [comment]
Hi @joeySeal ,

did you already try:
- uninstall RC1
- reboot system
- install RC2

If this also not working, please attach the full octoprint.log file.

**Comment by joeySeal** [comment]
@OllisGit how should I be installing? Via URL? (https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/latest/download/master.zip) or from the plugin manager. It does not appear in the plugin repo search.

**Comment by Putzi76** [comment]
> Hi @joeySeal ,
> 
> did you already try:
> 
> * uninstall RC1
> * reboot system
> * install RC2
> 
> If this also not working, please attach the full octoprint.log file.

it works for me.
Thanks

**Comment by OllisGit** [comment]
@joeySeal 
URL as mentioned in Homepage: https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/latest/download/master.zip

**Comment by karnwatcharasupat** [comment]
@OllisGit I just looked at `setup.py` of rc2 and it seems that the plugin version is not updated

```
# The plugin's version. Can be overwritten within OctoPrint's internal data via __plugin_version__ in the plugin module
plugin_version = "1.0.0rc1.1"
```

**Comment by OllisGit** [comment]
Hi @joeySeal ,
Damm, I forgot to push the setup file with the new version-number.

If you did a clean installation, you should receive rc2 (only with wrong version number), but updating from rc1.1 to rc2 could not work.

I will improve my build/releasmanagement, so that the setup version-number is the same as the git release-number.

Now rc2.1 is out, please test and give feedback.

Thx, Olli

**Comment by b-morgan** [comment]
I have rc2.1 installed but I still get an update available message, see attached.
![PrintHistory](https://user-images.githubusercontent.com/1547854/68414695-e38d0180-014d-11ea-9937-bcecb6e13933.png)
If there is something else you need from me, let me know.

**Comment by b-morgan** [comment]
I notice from the above screenshot that the name of the plugin in the manager is "Job History" but the project is PrintJobHistory. Should the two be more similar?

**Comment by OllisGit** [comment]
Hi @b-morgan ,
thanks a lot for pointing it out to me.

1) You installed the current version "rc2.1" and in the right popup the previous plugin "rc2" is mentioned. I think Octoprint has some "challenges" to identify the right number, so I removed the old "rc2" from my github release-panel. That should solve the issue.
2) I am not really "lucky" with the name "PrintJobHistory", so the idea was to shorten that Name and reuse the internal PluginId, but that is confusing. I will change that in the next version.

Again, thanks for your testing support!
Olli
