### ISSUE TITLE
Take Thumbnail from UltimakerFormatPackage-Plugin

### ISSUE THREAD

**Issue by alexandrkut** [OllisGit/OctoPrint-PrintJobHistory#22]
Hello!
Installed UltimakerFormatPackage-Plugin, setup "Use Thumbnail from UltimakerFormatPackage-Plugin", but in history list all image captured from camera.

**Comment by OllisGit** [comment]
Hi @alexandrkut,
did you remove the other checkbox "Take snapshot after print"?

**Comment by alexandrkut** [comment]
No.
Thank you!
