### ISSUE TITLE
Seems to interfere with streaming video and spaghetti detective

### ISSUE THREAD

**Issue by rrauenza** [OllisGit/OctoPrint-PrintJobHistory#24]
![image](https://user-images.githubusercontent.com/1376251/77677570-1e50d400-6f4d-11ea-9ae0-5dfd967edb5d.png)

**Comment by OllisGit** [comment]
@rrauenza ????more details????

**Comment by rrauenza** [comment]
More of a heads up, I guess.  I didn't have time to troubleshoot as I was printing covid items so I disabled it.  Feel free to close.

**Comment by OllisGit** [comment]
Okay, feel free to rise a new issue with more details.
Good job: Maker vs. Virus
