### ISSUE TITLE
SKR mini E3 1.2 Part Fan wont work?

### ISSUE THREAD

**Issue by buckiebull** [OllisGit/OctoPrint-PrintJobHistory#26]
I've installed my SKR Mini E3 1.2 & 3.5 V3 Touch screen TFT onto my Ender 3 pro
but I cannot get the part fan to come on, it is installed in the Fan 0 position as shown!
Both the hot end fan works & the motherboard fan works!
I have also tried two other fans I have spare but do not work on the Fan 0 socket.
Any help please!

**Comment by OllisGit** [comment]
Hi @buckiebull ,
are you sure that you create the ticket in the right ticket-tracker?

This repository is related to Job-History and had nothing to do with Fan-Settings.

Maybe you should use the  OP-Forum to raise your question: https://community.octoprint.org/

**Comment by OllisGit** [comment]
No feedback -> closed!
