### ISSUE TITLE
your new release is working but question about Spool

### ISSUE THREAD

**Issue by villaje** [OllisGit/OctoPrint-PrintJobHistory#29]
Thanks for the update, finally working on my ender 3 pro. Does the Spool field ever get auto filled? 
https://tppr.me/U2b33
Never used your plugin before or seen it working so not sure if we have to Manually fill that every time. I do have FilamentManager installed and setup with a spool.

**Comment by OllisGit** [comment]
Hi @villaje ,

should work:
![image](https://user-images.githubusercontent.com/24205767/81609948-00dea900-93d9-11ea-9abc-9d8cd9d79768.png)
Did you select a spool (left side) before the print starts?
