### ISSUE TITLE
Uploading of image

### ISSUE THREAD

**Issue by stonefox1958** [OllisGit/OctoPrint-PrintJobHistory#30]
Hi
Need help.
When I upload a snapshot and see that "Snapshot Uploaded" has been done correctly, why doesn't the uploaded image appear in the box just above?
IS the path where these uploaded images change so I can easily access them myself?
Want to insert a picture I have lying myself!
![octoprint plugin - save history](https://user-images.githubusercontent.com/8201781/81330169-fef6ac00-909f-11ea-9c05-72e5b5f4c79d.jpg)

Steen from Denmark

**Comment by OllisGit** [comment]
Hi @stonefox1958 ,
thx for reporting this issue.

This is fixed in the latest RC Version.

Please test and give me a feedback.

Bye
Olli
