### ISSUE TITLE
Don't call optional plug-ins "Missing" Plug-ins

### ISSUE THREAD

**Issue by JohnOCFII** [OllisGit/OctoPrint-PrintJobHistory#31]
I installed and tested PrintJob History.  I may, or may not install your other plug-ins in the future.  The existing PrintJobHistory works well, but OctoPrint warns me very, very often that I'm missing plug-ins!  This is annoying.  Don't use this feature as a marketing billboard for your other plug-ins. 

Thank you.

<img width="556" alt="Screen Shot 2020-05-13 at 2 20 45 PM" src="https://user-images.githubusercontent.com/7844212/81889471-361a0100-9569-11ea-9696-6c424a97b484.png">

**Comment by OllisGit** [comment]
hmmm...just hit the checkbox "disable..." then you will never see this popup! 
Just read the content in the dialog, everytime it appears ;-)

Or does this checkbox don't work?

Btw. only "DisplayLayerProgress" is developed be me. The other plugins were developed by other Developers. So, it has absolutely nothing to do with a "marketing billboard"!!!

**Comment by JohnOCFII** [comment]
Thank you for your reply.

Yes, if I select the "disable Plugin-Dependency check" I do stop receiving the message.  My initial reluctance to that was that I did not know of that message was specific to your plug-in, or if it set that flag across ALL OctoPrint plug-ins.

Thanks,

John

**Comment by OllisGit** [comment]
Changed to "optional" in newest release 1.0.0.
