### ISSUE TITLE
[Enhancement] Option to make the history read only

### ISSUE THREAD

**Issue by FixxCZ** [OllisGit/OctoPrint-PrintJobHistory#33]
Hi, I'm running the printer in the small community environment where users have dedicated user login to Octoprint. I would like to use this plugin to measure each user usage of filament, but problem is that any user can delete the job history items to clear their activity. I assume it would be difficult to introduce a permission into the official permission groups to make it read only for only certain group of users. So good enough solution would be to make it possible to disable the job delete button in the settings for everyone, even for admins. If admin would need to remove some job, she/he can be enable temporarily in the settings.

**Comment by OllisGit** [comment]
Hi @FixxCZ ,

I think this would be a very good feature! I added this feature to my planing-board: 
https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1

To be honest, I never looked into the permission-concept of OctoPrint so I have no idea if its possible...should be. But I can also ask in the forum about some "implementation-snippets".

**Comment by OllisGit** [comment]
@FixxCZ fyi: it is possible to add custom plugin-specific permissions, BUT only since OP 1.4.......but this is a good excuse to only support OP 1.4 in the future, no backward compatibility any more ;-)
https://docs.octoprint.org/en/master/plugins/hooks.html?highlight=permission#additional_permissions_hook

**Comment by FixxCZ** [comment]
Sounds like plan :)  I currently resolved it by modifying the package and removing the buttons from the layout and it works for purpose I need it.

**Comment by OllisGit** [comment]
Hi @FixxCZ,

it took a while....but in the next release I added two new permissions: Edit and Delete-PrintJob.
![image](https://user-images.githubusercontent.com/24205767/149680158-e5d60679-efa2-4f1d-9b52-c21a5ae0de4e.png)
Also in the tab  list the delete and add functionality is gone.

The default groups "admin" and  "operator" will include theses permissions as a defualt, so you need to create your own group... or remove it from the operator.

**Comment by FixxCZ** [comment]
@OllisGit  Thanks a lot, you are the rockstar! It will help me a lot.

**Comment by OllisGit** [comment]
Hi @FixxCZ ,

new release is out and permission check is implemented.

Please test and give feedback.

Thx, in advance
Olli
