### ISSUE TITLE
Always ask to update to last version

### ISSUE THREAD

**Issue by Schawy** [OllisGit/OctoPrint-PrintJobHistory#36]
Hi,

I have installed the last version 1.0.0rc6.1 but i get always an popup to ask me to update to the V1.0.0rc6.

[image](https://drive.google.com/file/d/18OHBjYteRnrKDjcQkx80E_wFzPlgAi6v/view?usp=sharing)

Is it possible to check that ?

Thanks.

**Comment by OllisGit** [comment]
Hi @Schawy,

I can't see the image: "Access Denied", but you can just Copy&Paste the image into a comment textbox. Add a comment, put the image into the clipboard and paste the image into the comment box.

Regarding your mentioned issue, it looks like a OctoPrint-Bug..or missing feature.
I ask the community about the version-detection, see https://community.octoprint.org/t/ordering-of-version-numbering/20313

**Comment by Schawy** [comment]
![26-05-_2020_16-56-21](https://user-images.githubusercontent.com/65965255/82936771-5c8b6380-9f8f-11ea-93f9-2b595ac79482.png)
Hi @OllisGit know the picture 😉

**Comment by OllisGit** [comment]
Hi @Schawy ,
a technical description of the issue could be found in the above forum-link.

But I release Version 1.0.0. So, this issue is solved anyway.
