### ISSUE TITLE
Difference between not-installed and installed but disabled

### ISSUE THREAD

**Issue by b-morgan** [OllisGit/OctoPrint-PrintJobHistory#4]
I'm not sure if you can tell the difference but it took me a while to discover that DisplayLayerProgress was installed but it was disabled. If you can tell the difference, changing the message would be helpful.

**Comment by OllisGit** [comment]
Hi @b-morgan ,

the new Dialog-Text will look like this in the next version:
![image](https://user-images.githubusercontent.com/24205767/68422234-119b3180-01a0-11ea-8fdb-ffc31922e242.png)

**Comment by b-morgan** [comment]
Perfect!

**Comment by OllisGit** [comment]
Hi @b-morgan ,
new version rc3 is out. 
If you want to test...or if you have the time for a poll: ["What is the next big thing?"](https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/6 ) 

Thx,
Olli
