### ISSUE TITLE
[Feature Request] Table Selection Checkboxes

### ISSUE THREAD

**Issue by KenLucke** [OllisGit/OctoPrint-PrintJobHistory#43]
Please add selection checkboxes for each item, which could be selected and use to determine a number of jobs to be deleted or exported at one time.

This would be comprised of a manual checkbox next to each job, and a "Select All/Select All This Page/Toggle Selected" Drop-down menu at the top, which would be used by a "Delete Selected/Export Selected to CSV" option.

**Comment by OllisGit** [comment]
Good idea! I will put that to my backlog.

**Comment by OllisGit** [comment]
Btw. you can always clean the whole database via the plugin-settings menu!

**Comment by OllisGit** [comment]
The row selection feature is available in the version 1.8. 
Please test and give feedback.

BR
Olli

**Comment by KenLucke** [comment]
Will do.  I have it turned off at the moment, as it was getting tedious to delete all the jobs one at a time.  I'll turn it back on after current jobs are done and test.
