### ISSUE TITLE
Prusa Slicer Thumbnail is not used even though it is present in the GCode

### ISSUE THREAD

**Issue by NameOfTheDragon** [OllisGit/OctoPrint-PrintJobHistory#57]
I'm not getting the thumbnails as expected in the print job history. I have the option selected to "_`Use thumbnail (if provided) after print, instead of snapshot`_" selected. The thumbnail is definitely present because it's showing up in the file list window (screen shot)

![image](https://user-images.githubusercontent.com/1268490/84146987-84310000-aa54-11ea-8288-275686cbbd23.png)

My settings are as follows:
![image](https://user-images.githubusercontent.com/1268490/84147051-a75baf80-aa54-11ea-83df-73d16547a9fd.png)

I have attached the GCode file (downloaded from OctoPrint) that was used to print the item in the screen shots. You will see that it contains 2 thumbnails, 16x16 and 220x124

[EXTRUDER_Gear_0.2n_0.1mm_PETG_ENDER3_55m.zip](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/4752124/EXTRUDER_Gear_0.2n_0.1mm_PETG_ENDER3_55m.zip)

**Comment by NameOfTheDragon** [comment]
By the way, thanks for a great plugin. I really like the idea of keeping a log of printed items and hopefully later being able to view stats.

**Comment by OllisGit** [comment]
Hi @NameOfTheDragon ,

the new release is out V1.4.0, BUT I only changed the text and not the default behaviour.

Because "you" prefer the thumbnail and other people prefer the real deal and want a picture from the cam instead of the slicer-thumbnail.
So, I need to find an "nice" UI-Design how to handle such configuration. 

Ideas are welcome (keep in mind, that in future you can grab several pictures)!!!

**Comment by NameOfTheDragon** [comment]
In your screen shot for release 1.4.0, the text hasn't actually changed... I'm running a print right now but as soon as it finishes (~ 1 hour) I'll install the update and see if it has actually changed.

In my previous post (last paragraph) I suggested how to handle this:

> Perhaps what is needed is a toggle control that toggles between "prefer thumbnails" or "prefer camera"?

The toggle control would be disabled if only one source is enabled. As soon as 2 sources are enabled, then you get to choose which one has priority.

You could default it to "Prefer camera" so that it's a non-breaking change for existing users.

**Comment by NameOfTheDragon** [comment]
I've updated to the latest release and yeah, the text hasn't changed. That's OK, the text describes the exact behavior I want ;-) What I want it to be able to prioritize thumbnails over snapshots.
![image](https://user-images.githubusercontent.com/1268490/84530305-d1be9e80-acda-11ea-8c99-fd3aee598c24.png)

P.S. You've labelled this issue as a "question" - it actually isn't. Depending on your perspective, it is either a bug or an enhancement request.

**Comment by OllisGit** [comment]
Hi @NameOfTheDragon ,
in the latest version 1.6.0 I added a new feature to select the prefered image-source.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by NameOfTheDragon** [comment]
I think we can probably close this now. Thanks for all your work on this.

**Comment by Doprintityourself** [comment]
I have installed 1.17 of Printjobhistory but i do not get any Thumbnails any more:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/70262325/215453295-37e42de8-5167-417e-bce1-ec5145dd714c.png">
I have Slicer Thumbnails latest 1.0.1 installed and can see every Thumbnail in  the status section but not in Print Job History after printing
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/70262325/215455515-b75cafb7-7b4d-4d79-aa19-1873bf067c76.png">
My not be a hint but it stopped arround beginning of November but not consequently as you see two are without end on still after beginning again with thumb, after 4.11.2022 no more thumb was created
<img width="785" alt="image" src="https://user-images.githubusercontent.com/70262325/215456815-57b0304f-b636-4ebb-a530-992efa15cc64.png">

**Comment by mikaeltulldahl** [comment]
Hello I can second that it broke recently. It seems related to which slicer I'm using. With Prusaslicer 2.6.0-alpha5+win64 I will only get a photo in the end. I picked up an old .3mf project and sliced with Prusaslicer 2.5.0+win64 and got a thumbnail in the print job history
