### ISSUE TITLE
Populate Spool... fields from PrusaSlicer gcode comments

### ISSUE THREAD

**Issue by 6ffm70** [OllisGit/OctoPrint-PrintJobHistory#58]
**Background**
I have been waiting for a plugin like this. Currently, we record our prints in a LibreOffice table, and it's a lot of typing for something your plugin may do automatically.

**Problem**
We don't want to use the filament manager plugin to maintain our currently 74 spools, but still want to see our chosen spool description in the print history.

**Possible solution**
We're using PrusaSlicer and the current release returns our chosen spool description under 
`; filament_settings_id = "chosen spool description"`
Would it be possible to have a checkbox or a setting that the field _Spool_, _Material_ and _Vendor_ are populated from the settings commentary in the PrusaSlicer gcode files?

_Spool_ = `; filament_settings_id`
_Material_ = `; filament_type`
_Vendor_ = `; filament_vendor`  // though at the moment it says `(Unknown)`, and I can see no means to populate that field in PrusaSlicer

**Comment by OllisGit** [comment]
Hi @6ffm70 ,

sounds like a good idea!

It looks like that this feature (exporting material-info) is not a supported for Cura and only available for PrusaSlicer.

**Comment by OllisGit** [comment]
this ticket is related to #104

Short: Grab field-values from gcode instead from other plugins or own calculation.

@6ffm70 maybe you have a suggestion how a UI could look like.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by 6ffm70** [comment]
Hello @OllisGit , thank you for getting back on this.

My proposal to get the filament name from PrusaSlicer into the PrintJobHistory entry is the following:

![image](https://user-images.githubusercontent.com/50849255/106582179-fefade00-6543-11eb-88f4-c36979c4f806.png)
1.) Name as saved in P/S

![image](https://user-images.githubusercontent.com/50849255/106582249-12a64480-6544-11eb-99c8-8bc892c5d7f1.png)
2.) Name as transmitted via gcode

![image](https://user-images.githubusercontent.com/50849255/106582369-35385d80-6544-11eb-8ba2-24b340ef4cf3.png)
3.) Additional option in P/J/H settings

![image](https://user-images.githubusercontent.com/50849255/106582472-4da87800-6544-11eb-9245-e6c0a3d8f0ec.png)
4.) Pre-populated form field when print job window pops up

**Comment by 6ffm70** [comment]
In another finding: I sometimes use multiple spools per print, which are manually changed during on print job.

In PrusaSlicer, it looks like this:
![image](https://user-images.githubusercontent.com/50849255/106583812-c956f480-6545-11eb-8d9e-d3df293628ae.png)

In the gcode, it looks like this:
![image](https://user-images.githubusercontent.com/50849255/106583996-f86d6600-6545-11eb-91e4-ab8246c19035.png)

Eight different types is an extreme example; however this might occur across the field from time to time. It might make sense knowing this beforehand.

**Comment by OllisGit** [comment]
fyi: I am starting writing a kind of concept to implement such feature. I am looking for a simple and easy to use solution.
https://github.com/OllisGit/OctoPrint-PrintJobHistory/wiki/GCodeSpoolInfo
