### ISSUE TITLE
failed/cancelled jobs aren't being recorded

### ISSUE THREAD

**Issue by Zouljiin** [OllisGit/OctoPrint-PrintJobHistory#67]
I've had to cancel several jobs to to some problem or another but the plugin never pops up to confirm usage and such. Nor is it available in the history, despite the option to filter by failed jobs.

**Comment by OllisGit** [comment]
Hi @Zouljiin ,

please check your Plugin-Settings. You need to set the "always" flag.
![image](https://user-images.githubusercontent.com/24205767/88713142-1e3f2b80-d11b-11ea-8e3c-e521b976acd0.png)

**Comment by Zouljiin** [comment]
i dont know how i missed that. I just got done trying to see if it was a setting. i think i read it as capturing an image. thanks.
