### ISSUE TITLE
Spool improvements

### ISSUE THREAD

**Issue by joeynuggetz** [OllisGit/OctoPrint-PrintJobHistory#69]
Having to enter the spool name and type it in exactly as the spool you used before makes it tough to stay consistent with tracking how much is left on a spool. Maybe the software can tell you how much is left on a spool and implement a proper spool management system

**Comment by OllisGit** [comment]
Hi @joeynuggetz ,

the current implementation is using FilamentManager more or less as a "workaround".
My goal is to finalize my [SpoolManager-Plugin ](https://github.com/OllisGit/OctoPrint-SpoolManager) and "combine" both plugins.

Hopefully I can finish this end of the month!
