### ISSUE TITLE
[Feature request]: Timeframe statistics

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-PrintJobHistory#74]
Most requested feature is "Statistic Report Diagram" (see https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/6), but implementing Diagrams takes a lot of effort (for me, I am not a JS/UI-Expert).

I decided to implement (in the future) the approach to send every event (that OP + Plugins create) is send to an "Influx-Database-Sink). See https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1#card-27067834 

BUT: It should be possible to implement just a simple "timeslot picker" (start/end date and give  an result tableview of several aggregated values, like:

- Used Length/Weight
- Duration
- Filesize
- Used Material (Array)
- Used Spools (Array)
- Print result (count of each status)

![image](https://user-images.githubusercontent.com/24205767/90647605-c6d33d80-e238-11ea-80f3-66513c5454ef.png)

![image](https://user-images.githubusercontent.com/24205767/90647873-1c0f4f00-e239-11ea-9de5-fe0ff66b75dc.png)

**Comment by osm-3d** [comment]
As I mentioned in a email to Olli the idea of having the ability to track total print time and filament length seems very appealing. Mock-up screenshots look much better than I imagined

**Comment by OllisGit** [comment]
Implemented in Version 1.8+
