### ISSUE TITLE
[Feature request]: Integrate SpoolManager-Plugin

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-PrintJobHistory#75]
As the title says ;-)

**Comment by Lumute** [comment]
Yes, +1 for this one, FilamentManager seems to be abandoned and no one has picked it up. SpoolManager 1.0 was just released and its looking great...

**Comment by TDI4** [comment]
+1 on this, would be really nice. SpoolManager looks more detailed than Filament Manager. I would appreciate.

Thank you in advance!

**Comment by cwbullet** [comment]
I would agree with this once Spoolmanager supports an external database.

**Comment by ofc587a87** [comment]
+1 for me too. After migrating octoprint to Python3 (recomeded by octroprint blog), FilamentManager gets disabled, as it doesn't support python3.

**Comment by cwbullet** [comment]
This has happened to me with Printer History, statistics 2.0, and now filament manager.

**Comment by SM-26** [comment]
so far I prefer your sool manager over filament manager.
and print history integration seems like the next logical step.

If there is anything I could do to help, just say the word.

**Comment by cwbullet** [comment]
I think if spool manager were able to have a central database for multiple printers/octoprints, I would switch tomorrow.

**Comment by 6ffm70** [comment]
+1 I thought you were to do that anyway, Olli! 

For this one, I'd love to see some filament recognition from the gcode, whereever possible - like discussed in [https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/58](url)

**Comment by condraka** [comment]
++1 also.  Like SpoolManager better than Filament Manager.   
+2 for external database to use with multiple machines on different Octopi's running on those machines....

**Comment by fabiradi** [comment]
There is a PR, which might be a good start (or even solve this issue completely?), see https://github.com/OllisGit/OctoPrint-PrintJobHistory/pull/102

**Comment by OllisGit** [comment]
fyi: Currently I have some "private challenges to solve", thats the reason why It takes so long to release a new version, sorry!

Today I released a new development version (1.11.0). This version include the option for selecting the SpoolManager-Plugin for filament tracking.
**BUT you need the newest Version of SpoolManager 1.4.0+ and an other BUT: this version is not released yet!**

So, please be patient it will take some time.

Thx, in advance
Olli

**Comment by OllisGit** [comment]
Try to use the lastest PJH-Plugin V1.14.0 and SpoolManger V1.4.0, that should work!

Please test and give feedback!
Olli

**Comment by condraka** [comment]
Yes 

Carl E. Ondraka
