### ISSUE TITLE
Is there an easy way to add prints that were not done with OctoPrint?

### ISSUE THREAD

**Issue by Lumute** [OllisGit/OctoPrint-PrintJobHistory#77]
As per the title, I printed a couple of things directly from SD and would be great f I could add them to the history in an easy way... I realize I could probably create a csv with the info and import it but that's a lot of work...

**Comment by OllisGit** [comment]
Hi @Lumute,
I added this feature to the latest version 1.10.0.

Please test and give feedback.
Thx, in advance
Olli
