### ISSUE TITLE
Filament mismatch with MMU 

### ISSUE THREAD

**Issue by Syl20-94** [OllisGit/OctoPrint-PrintJobHistory#82]
hello since few print I figure out that datas collected at end of print are not correct, 
I used a MMU Unit and the end dialog catch data from spool 1 which is not correct, so I have to it manually (I have  OctoPrint-Mmu2filamentselect install to manage differents spool)
should it be possible to collect these datas in order to  get all value ?

thank a lot, please lets me know if my explaination are clear enough

**Comment by OllisGit** [comment]
Hi @Syl20-94 ,

currently there is no support for MultiTools. You need to select the single ToolID in front of a print in the Plugin-Settings. Then the extruded length is picked up for that tool after the print.

The MultiTool feature will be available with the integration of the SpoolManager....could take a while.

BR
Olli
