### ISSUE TITLE
[Feature request]: Integrate OctoPrint-TPLinkSmartplug plugin 

### ISSUE THREAD

**Issue by emmesp** [OllisGit/OctoPrint-PrintJobHistory#85]
OctoPrint-TPLinkSmartplug adds power cost when using a energy monitor smartplug like the HS110
It will be awesome to have this as part of the job history
![image](https://user-images.githubusercontent.com/53792065/93505350-f9c02e00-f8d7-11ea-977d-2aeec63328ce.png)

https://github.com/jneilliii/OctoPrint-TPLinkSmartplug

**Comment by OllisGit** [comment]
Hi @emmesp ,

it is already on my roadmap.

BR
Olli
