### ISSUE TITLE
Wrong statistics

### ISSUE THREAD

**Issue by spanzetta** [OllisGit/OctoPrint-PrintJobHistory#87]
See screenshots and attached CSV..
The total **Length** and **Weight** are definitively wrong
Pls check it
Thanks

[OctoprintPrintJobHistory.zip](https://github.com/OllisGit/OctoPrint-PrintJobHistory/files/5252174/OctoprintPrintJobHistory.zip)

![Clipboard01](https://user-images.githubusercontent.com/49818743/93717569-ee3e6280-fb76-11ea-89ad-83554642f241.jpg)

**Comment by spanzetta** [comment]
Hi @OllisGit 
any comments?
Thanks

**Comment by OllisGit** [comment]
Hi @spanzetta ,

can't see any issue:
![image](https://user-images.githubusercontent.com/24205767/93927526-4ad98300-fd19-11ea-89c1-a0c738ae90e4.png)

Next time, please add more informations. "definitively wrong" is not helpful!

Something like this:
```
expected value: 123, plugin-value: 321
```
Thx, in advance
Olli

**Comment by spanzetta** [comment]
dear @OllisGit 
Sorry but I was sure it was so evident..
You can read in the first row of the screenshots that the Timeframe selection is ALL (Timeframe All/Filter ALL) .. but the data (First/Last) are from 01.09 to 07.09.. so as Total statistics .. data is wrong  (I wanted to calculate the Total prints)
I hope is more clear now?
If not pls let me know
Thanks

**Comment by spanzetta** [comment]
Do you confirm is it clear now?
Thanks

**Comment by OllisGit** [comment]
Hi @spanzetta ,

it is fixed in the latest version 1.10.0.

Please test and give feedback.

Thx, ,in advance
Olli

**Comment by spanzetta** [comment]
Great news!
Thanks you
I'll test and let you know
Have a nice day

**Comment by spanzetta** [comment]
Now it is fine..
Thank you so much
