### ISSUE TITLE
[Feature request]: Add "printed X times" to gcode

### ISSUE THREAD

**Issue by Chrismettal** [OllisGit/OctoPrint-PrintJobHistory#91]
I know i can export the whole .csv and add up every time i see a specific name in that list, but having a "Number of successful prints" and "Number of failed prints" for every gcode could be helpful to some.

Over the last two years i have reprinted a single gcode a few hundred times and i lost control about how much filament went through the printer just for this part. Would be interesting to see how many failed ones i had during that time.

**Comment by OllisGit** [comment]
Hi @Chrismettal ,
interesting feature, I will put this to my long term-planing board.

BR
Olli
