### ISSUE TITLE
[Feature Request] Reprint

### ISSUE THREAD

**Issue by TodWulff** [OllisGit/OctoPrint-PrintJobHistory#94]
Good day.  Thank you for this most useful plugin.  It is very much appreciated.

I've read the docs herein.  I've reviewed the open issues herein.  I didn't note anything similar to my request, other than a tangentially related one for cloning.  I am not able to determine if this is already incorporated into the plugin.  If it is, please forgive.

As a respectful suggestion, it would be nice, for my workflow purposes, to be able to scroll the list of prints previously done and, if I come across one that I wished to reprint, to be able to initiate the reprint right from the PJH plugin, either by clicking a reprint icon (enabled if the file still exists in local storage and has a CRC matching that which was generated at initial print job completion), or possibly have it in a context menu when a record is right clicked on in the PJH Table (again, disabled if the file no longer exists or has a different CRC).

Take care.

-t

**Comment by TodWulff** [comment]
Is this feature available in the current builds - the ability to reprint from within PJH?

**Comment by peta** [comment]
I was looking for the exact same functionality already multiple times but couldnt find it. Therefore I was about to create a feature request issue about this. 

When we consider PJH as a complete solution for recording every executed along with 3d model thumbnail, webcam snapshots, description and -- most importantly -- all kinds of metadata (filament used, costs, slicer settings asf.) the gcode file shall be included in the persistent PJH database, too. Which in turns makes a "Re-print" feature the logical consequence of it.

I would even support work on this using a PayPal tip jar or Patreon.

**Comment by OllisGit** [comment]
Hi,
yes this is a really "need" feature and this is also already on my roadmap (long-term)
https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/21

Why "long-term":
- Currently the used gcode is not stored in the database, so reprinting could only be done if the file is still in the filesystem in the same location as the last print
- So, storing the file in the database is a better choice. Also the images are not stored in the DB. It is planed to store "everything" in the database and this should be implemented together with the external database-feature.

Well, I have a lot of stuff to do with my other plugins as well....please be patient...its on my list ;-)

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
fyi: Feature is already planed (login-term), see https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1#card-45793778
I closed this issue to cleanup the "bug-tracking", but the feature is still planed (if not, it will be moved to column done in future).
