### ISSUE TITLE
Save function not being found (running two instances)

### ISSUE THREAD

**Issue by MadeforMaking** [OllisGit/OctoPrint-PrintJobHistory#95]
I've not been able to make changes to my print-jobs recently due to the save function not being successful. The developers console shows a 404 for this PUT request:

"PUT http://octopi.local:5001/plugin/PrintJobHistory/storePrintJob/66 404 (NOT FOUND)"

Any idea what could be happening or what I should try and do.

I'm running 2 instances on 1 pi, would this be an issue for the plugin?

**Comment by OllisGit** [comment]
Hi @MadeforMaking,

please look into the Storage file location of the plugin. If both instances use the same database file location it won't work.
![image](https://user-images.githubusercontent.com/24205767/104494972-738ecc80-55d7-11eb-8d49-6694609cb01e.png)

**Comment by MadeforMaking** [comment]
I will have a look this week and will get back to this issue, thanks.

**Comment by MadeforMaking** [comment]
The 2 paths are different
`/home/pi/.octoprint/data/PrintJobHistory/printJobHistory.db`
`/home/pi/.octoprint2/data/PrintJobHistory/printJobHistory.db`

I haven't been near octoprint in a while, so something must have changed after restarting the system. I am able to save changes so I am closing this issue.
