### ISSUE TITLE
[Feature request] Consider 3d Printer with multiple heads

### ISSUE THREAD

**Issue by amemo06** [OllisGit/OctoPrint-PrintJobHistory#96]
That plugin is pretty nice. Thanks for it. 
Print job history does not consider at the moment printers with multiple heads. Only the first head is considered thus leading to no information about spool used for the other heads and their consumptions/costs
It would be great if it could considers printers with multiple heads

**Comment by OllisGit** [comment]
Hi @amemo06 ,

already on my roadmap: https://github.com/OllisGit/OctoPrint-PrintJobHistory/projects/1 Long-Term column
