### ISSUE TITLE
[Feature request] Show edit dialog only on failed prints

### ISSUE THREAD

**Issue by MadeforMaking** [OllisGit/OctoPrint-PrintJobHistory#99]
If I have a good print setup and things are working well with the data gathered, I don't really want to see the dialog after every print. I would like edit the job for when there is a problem and the print has failed.

It encourages me to enter information when there is a problem. This way I can look at the data and see trends etc and see my explanation.

**Comment by OllisGit** [comment]
Hi @MadeforMaking ,

good idea. I will implement this enhancement in one of the next releases.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by MadeforMaking** [comment]
Thanks @OllisGit and we all need time away. Your doing great work.

**Comment by OllisGit** [comment]
fyi: Currently I have some "private challenges to solve", thats the reason why It takes so long to release a new version, sorry!

Hi @MadeforMaking, 
today I released a new development version (1.11.0). This feature is now available, please test and give feedback.

Thx, in advance for testing
Olli
